# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "goose-1.0.0-e9MzMGKcAgD7vlp_acJYt6g430wQcrAxUKWHEEF0_Hcc";
    path = fetchgit {
      url = "https://github.com/luxluth/goose";
      rev = "387de965800bf0f6116d51f45a9412cba0801975";
      hash = "sha256-SWx6eoQ47DcIdQEdTaKb7b2Rn/6qB+XhCYTBMtMrGGw=";
    };
  }
]
